### ISSUE TITLE
Typo in DropboxPersisten.js file name

### ISSUE THREAD

**Issue by fdattein** [garyhodgson/openscad.net#10]
Hi there,

I can't open up the site at: http://garyhodgson.github.com/openscad.net/
It can't find the file http://garyhodgson.github.com/openscad.net/js/app/DropboxPersistence.js because the file name is DropBoxPersistence.js with capital "B"
- I am using chrome. (no problem on Firefox)

Cheers,
Franklin

**Comment by garyhodgson** [comment]
Thanks Franklin, it should be fixed now.
