### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by ghost** [garyhodgson/openscad.net#12]
Please could you specify the license under which you have released your code? Thanks!

N.B. As OpenSCAD.net is a web application, my preference is strongly for the [AGPLv3](https://en.wikipedia.org/wiki/Affero_General_Public_License), if it's compatible with the codebase you've extended.

**Comment by garyhodgson** [comment]
Hi @sampablokuper,  

I had think about it and I think that because the project is a port of OpenSCAD I should continue their license which is GPLv2.

I hope this aligns with your preferences.

**Comment by ghost** [comment]
GPLv2 is much better than no license! Thanks! :)
