### ISSUE TITLE
Dropbox Authorization redirection callback bug

### ISSUE THREAD

**Issue by 0x6e69636f** [garyhodgson/openscad.net#14]
When I try to connect to Dropbox, I'm redirected to the authorization page and when accepting, I get redirected to my OpenScad sketch for one second then back to the authorization page. If I try to close the tab and get back to openscad.net, I get quickly redirected to the authorization page again and can't access my sketch anymore.
Happened with Firefox & Chrome on Windows 7 and Firefox on OSX

**Comment by garyhodgson** [comment]
Hmm, it's been a while since I looked at this app. It sounds like a change to the way dropbox works might be the cause.  I'll have a look.

**Comment by garyhodgson** [comment]
Hi @nicolasbd - I updated the API settings and got it working again, but due to changes in the Dropbox OAuth API it will only work via a https protocol - and so not for the custom domain (openscad.net) The alternative domain can work over https though: https://garyhodgson.github.io/openscad.net

**Comment by 0x6e69636f** [comment]
Ok great, thanks !
