### ISSUE TITLE
Dropbox error "only limited set of users..."

### ISSUE THREAD

**Issue by fdattein** [garyhodgson/openscad.net#9]
Hi,

I am getting the error "Only a limited set of users can get an access token while this app is in development mode".

I an running a local copy of openscad.net.

Any thoughts?

Thanks

**Comment by garyhodgson** [comment]
Hi there,  thanks for the heads up.  I hadn't yet changed the dropbox api status from development - i'll do that tonight when I get time.

Cheers,
Gary

**Comment by garyhodgson** [comment]
Hi again, I've submitted the app for Dropbox production status. In the mean time I turned on the developer preview option which allows up to 5 people to test the app, so you should be good to test.

It's still a work in progress, and there are a couple of insidious bugs that I need to fix (e.g. the involute gear script doesn't work), but for playing with, and basic scripts it seems to work ok.

Cheers,
Gary
